### ISSUE TITLE
Python error, unicode error,

### ISSUE THREAD

**Issue by red-co** [renathossain/vscode-markdown-runner#9]
change 
```
coderunner.ts,
line107, 
....intert(0, '${document.... 
to intert(0, r'${document...
```
Test,
```python
Print("hello")
```

**Comment by renathossain** [comment]
Fixed. Could you please let me know which platform you're using and share the error message you’re encountering? I’d really appreciate it.

**Comment by red-co** [comment]
x64, Window 11,
unicode error,

**Comment by renathossain** [comment]
Thanks for your feedback!
